// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: product/product.proto

package productPb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProductList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Product             `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Meta          *Metadata              `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductList) Reset() {
	*x = ProductList{}
	mi := &file_product_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductList) ProtoMessage() {}

func (x *ProductList) ProtoReflect() protoreflect.Message {
	mi := &file_product_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductList.ProtoReflect.Descriptor instead.
func (*ProductList) Descriptor() ([]byte, []int) {
	return file_product_product_proto_rawDescGZIP(), []int{0}
}

func (x *ProductList) GetData() []*Product {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ProductList) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	TypeSize      string                 `protobuf:"bytes,3,opt,name=type_size,json=typeSize,proto3" json:"type_size,omitempty"`
	Image         string                 `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
	DefaultPrice  uint64                 `protobuf:"varint,6,opt,name=default_price,json=defaultPrice,proto3" json:"default_price,omitempty"`
	Price         uint64                 `protobuf:"varint,7,opt,name=price,proto3" json:"price,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_product_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_product_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_product_product_proto_rawDescGZIP(), []int{1}
}

func (x *Product) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetTypeSize() string {
	if x != nil {
		return x.TypeSize
	}
	return ""
}

func (x *Product) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Product) GetDefaultPrice() uint64 {
	if x != nil {
		return x.DefaultPrice
	}
	return 0
}

func (x *Product) GetPrice() uint64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Product) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Product) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Product) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type GeneralResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *General               `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneralResponse) Reset() {
	*x = GeneralResponse{}
	mi := &file_product_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneralResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneralResponse) ProtoMessage() {}

func (x *GeneralResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneralResponse.ProtoReflect.Descriptor instead.
func (*GeneralResponse) Descriptor() ([]byte, []int) {
	return file_product_product_proto_rawDescGZIP(), []int{2}
}

func (x *GeneralResponse) GetData() *General {
	if x != nil {
		return x.Data
	}
	return nil
}

type General struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *General) Reset() {
	*x = General{}
	mi := &file_product_product_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *General) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*General) ProtoMessage() {}

func (x *General) ProtoReflect() protoreflect.Message {
	mi := &file_product_product_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use General.ProtoReflect.Descriptor instead.
func (*General) Descriptor() ([]byte, []int) {
	return file_product_product_proto_rawDescGZIP(), []int{3}
}

func (x *General) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GeneralIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneralIdRequest) Reset() {
	*x = GeneralIdRequest{}
	mi := &file_product_product_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneralIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneralIdRequest) ProtoMessage() {}

func (x *GeneralIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_product_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneralIdRequest.ProtoReflect.Descriptor instead.
func (*GeneralIdRequest) Descriptor() ([]byte, []int) {
	return file_product_product_proto_rawDescGZIP(), []int{4}
}

func (x *GeneralIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GeneralFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Q             string                 `protobuf:"bytes,1,opt,name=q,proto3" json:"q,omitempty"`
	OrderBy       string                 `protobuf:"bytes,2,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	Limit         uint32                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        uint32                 `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	Sort          string                 `protobuf:"bytes,5,opt,name=sort,proto3" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneralFilter) Reset() {
	*x = GeneralFilter{}
	mi := &file_product_product_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneralFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneralFilter) ProtoMessage() {}

func (x *GeneralFilter) ProtoReflect() protoreflect.Message {
	mi := &file_product_product_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneralFilter.ProtoReflect.Descriptor instead.
func (*GeneralFilter) Descriptor() ([]byte, []int) {
	return file_product_product_proto_rawDescGZIP(), []int{5}
}

func (x *GeneralFilter) GetQ() string {
	if x != nil {
		return x.Q
	}
	return ""
}

func (x *GeneralFilter) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

func (x *GeneralFilter) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GeneralFilter) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GeneralFilter) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

type Metadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         uint32                 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_product_product_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_product_product_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_product_product_proto_rawDescGZIP(), []int{6}
}

func (x *Metadata) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_product_product_proto protoreflect.FileDescriptor

const file_product_product_proto_rawDesc = "" +
	"\n" +
	"\x15product/product.proto\x12\tproductPb\x1a(google/api/annotations/annotations.proto\x1a)google/protobuf/timestamp/timestamp.proto\"^\n" +
	"\vProductList\x12&\n" +
	"\x04data\x18\x01 \x03(\v2\x12.productPb.ProductR\x04data\x12'\n" +
	"\x04meta\x18\x02 \x01(\v2\x13.productPb.MetadataR\x04meta\"\xcc\x02\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\ttype_size\x18\x03 \x01(\tR\btypeSize\x12\x14\n" +
	"\x05image\x18\x05 \x01(\tR\x05image\x12#\n" +
	"\rdefault_price\x18\x06 \x01(\x04R\fdefaultPrice\x12\x14\n" +
	"\x05price\x18\a \x01(\x04R\x05price\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\"9\n" +
	"\x0fGeneralResponse\x12&\n" +
	"\x04data\x18\x01 \x01(\v2\x12.productPb.GeneralR\x04data\"#\n" +
	"\aGeneral\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\"\n" +
	"\x10GeneralIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"z\n" +
	"\rGeneralFilter\x12\f\n" +
	"\x01q\x18\x01 \x01(\tR\x01q\x12\x19\n" +
	"\border_by\x18\x02 \x01(\tR\aorderBy\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\rR\x06offset\x12\x12\n" +
	"\x04sort\x18\x05 \x01(\tR\x04sort\" \n" +
	"\bMetadata\x12\x14\n" +
	"\x05count\x18\x01 \x01(\rR\x05count2\xcf\x04\n" +
	"\x0eProductService\x12b\n" +
	"\rCreateProduct\x12\x12.productPb.Product\x1a\x1a.productPb.GeneralResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/api/v1/product/create\x12m\n" +
	"\rDeleteProduct\x12\x1b.productPb.GeneralIdRequest\x1a\x1a.productPb.GeneralResponse\"#\x82\xd3\xe4\x93\x02\x1d\"\x1b/api/v1/product/delete/{id}\x12`\n" +
	"\x0eGetListProduct\x12\x18.productPb.GeneralFilter\x1a\x16.productPb.ProductList\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/api/v1/product/list\x12`\n" +
	"\n" +
	"GetProduct\x12\x1b.productPb.GeneralIdRequest\x1a\x12.productPb.Product\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/api/v1/product/view/{id}\x12b\n" +
	"\rUpdateProduct\x12\x12.productPb.Product\x1a\x1a.productPb.GeneralResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/api/v1/product/update\x12B\n" +
	"\rRpcGetProduct\x12\x1b.productPb.GeneralIdRequest\x1a\x12.productPb.Product\"\x00B/Z-github.com/YogiTan00/Reseller/proto;productPbb\x06proto3"

var (
	file_product_product_proto_rawDescOnce sync.Once
	file_product_product_proto_rawDescData []byte
)

func file_product_product_proto_rawDescGZIP() []byte {
	file_product_product_proto_rawDescOnce.Do(func() {
		file_product_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_product_product_proto_rawDesc), len(file_product_product_proto_rawDesc)))
	})
	return file_product_product_proto_rawDescData
}

var file_product_product_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_product_product_proto_goTypes = []any{
	(*ProductList)(nil),           // 0: productPb.ProductList
	(*Product)(nil),               // 1: productPb.Product
	(*GeneralResponse)(nil),       // 2: productPb.GeneralResponse
	(*General)(nil),               // 3: productPb.General
	(*GeneralIdRequest)(nil),      // 4: productPb.GeneralIdRequest
	(*GeneralFilter)(nil),         // 5: productPb.GeneralFilter
	(*Metadata)(nil),              // 6: productPb.Metadata
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_product_product_proto_depIdxs = []int32{
	1,  // 0: productPb.ProductList.data:type_name -> productPb.Product
	6,  // 1: productPb.ProductList.meta:type_name -> productPb.Metadata
	7,  // 2: productPb.Product.created_at:type_name -> google.protobuf.Timestamp
	7,  // 3: productPb.Product.updated_at:type_name -> google.protobuf.Timestamp
	7,  // 4: productPb.Product.deleted_at:type_name -> google.protobuf.Timestamp
	3,  // 5: productPb.GeneralResponse.data:type_name -> productPb.General
	1,  // 6: productPb.ProductService.CreateProduct:input_type -> productPb.Product
	4,  // 7: productPb.ProductService.DeleteProduct:input_type -> productPb.GeneralIdRequest
	5,  // 8: productPb.ProductService.GetListProduct:input_type -> productPb.GeneralFilter
	4,  // 9: productPb.ProductService.GetProduct:input_type -> productPb.GeneralIdRequest
	1,  // 10: productPb.ProductService.UpdateProduct:input_type -> productPb.Product
	4,  // 11: productPb.ProductService.RpcGetProduct:input_type -> productPb.GeneralIdRequest
	2,  // 12: productPb.ProductService.CreateProduct:output_type -> productPb.GeneralResponse
	2,  // 13: productPb.ProductService.DeleteProduct:output_type -> productPb.GeneralResponse
	0,  // 14: productPb.ProductService.GetListProduct:output_type -> productPb.ProductList
	1,  // 15: productPb.ProductService.GetProduct:output_type -> productPb.Product
	2,  // 16: productPb.ProductService.UpdateProduct:output_type -> productPb.GeneralResponse
	1,  // 17: productPb.ProductService.RpcGetProduct:output_type -> productPb.Product
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_product_product_proto_init() }
func file_product_product_proto_init() {
	if File_product_product_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_product_product_proto_rawDesc), len(file_product_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_product_product_proto_goTypes,
		DependencyIndexes: file_product_product_proto_depIdxs,
		MessageInfos:      file_product_product_proto_msgTypes,
	}.Build()
	File_product_product_proto = out.File
	file_product_product_proto_goTypes = nil
	file_product_product_proto_depIdxs = nil
}
