// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: transaction/transaction.proto

package transactionPb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransactionList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Transaction         `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Meta          *Metadata              `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionList) Reset() {
	*x = TransactionList{}
	mi := &file_transaction_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionList) ProtoMessage() {}

func (x *TransactionList) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionList.ProtoReflect.Descriptor instead.
func (*TransactionList) Descriptor() ([]byte, []int) {
	return file_transaction_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *TransactionList) GetData() []*Transaction {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *TransactionList) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IdName        string                 `protobuf:"bytes,2,opt,name=id_name,json=idName,proto3" json:"id_name,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ReturnItem    *wrapperspb.BoolValue  `protobuf:"bytes,4,opt,name=return_item,json=returnItem,proto3" json:"return_item,omitempty"`
	SalesDate     string                 `protobuf:"bytes,5,opt,name=sales_date,json=salesDate,proto3" json:"sales_date,omitempty"`
	Unit          uint32                 `protobuf:"varint,6,opt,name=unit,proto3" json:"unit,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_transaction_transaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_transaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_transaction_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *Transaction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Transaction) GetIdName() string {
	if x != nil {
		return x.IdName
	}
	return ""
}

func (x *Transaction) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Transaction) GetReturnItem() *wrapperspb.BoolValue {
	if x != nil {
		return x.ReturnItem
	}
	return nil
}

func (x *Transaction) GetSalesDate() string {
	if x != nil {
		return x.SalesDate
	}
	return ""
}

func (x *Transaction) GetUnit() uint32 {
	if x != nil {
		return x.Unit
	}
	return 0
}

func (x *Transaction) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type GeneralResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *General               `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneralResponse) Reset() {
	*x = GeneralResponse{}
	mi := &file_transaction_transaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneralResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneralResponse) ProtoMessage() {}

func (x *GeneralResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_transaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneralResponse.ProtoReflect.Descriptor instead.
func (*GeneralResponse) Descriptor() ([]byte, []int) {
	return file_transaction_transaction_proto_rawDescGZIP(), []int{2}
}

func (x *GeneralResponse) GetData() *General {
	if x != nil {
		return x.Data
	}
	return nil
}

type General struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *General) Reset() {
	*x = General{}
	mi := &file_transaction_transaction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *General) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*General) ProtoMessage() {}

func (x *General) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_transaction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use General.ProtoReflect.Descriptor instead.
func (*General) Descriptor() ([]byte, []int) {
	return file_transaction_transaction_proto_rawDescGZIP(), []int{3}
}

func (x *General) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GeneralIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneralIdRequest) Reset() {
	*x = GeneralIdRequest{}
	mi := &file_transaction_transaction_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneralIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneralIdRequest) ProtoMessage() {}

func (x *GeneralIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_transaction_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneralIdRequest.ProtoReflect.Descriptor instead.
func (*GeneralIdRequest) Descriptor() ([]byte, []int) {
	return file_transaction_transaction_proto_rawDescGZIP(), []int{4}
}

func (x *GeneralIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GeneralFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Q             string                 `protobuf:"bytes,1,opt,name=q,proto3" json:"q,omitempty"`
	OrderBy       string                 `protobuf:"bytes,2,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	Limit         uint32                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        uint32                 `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	Sort          string                 `protobuf:"bytes,5,opt,name=sort,proto3" json:"sort,omitempty"`
	StartDate     string                 `protobuf:"bytes,6,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,7,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneralFilter) Reset() {
	*x = GeneralFilter{}
	mi := &file_transaction_transaction_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneralFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneralFilter) ProtoMessage() {}

func (x *GeneralFilter) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_transaction_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneralFilter.ProtoReflect.Descriptor instead.
func (*GeneralFilter) Descriptor() ([]byte, []int) {
	return file_transaction_transaction_proto_rawDescGZIP(), []int{5}
}

func (x *GeneralFilter) GetQ() string {
	if x != nil {
		return x.Q
	}
	return ""
}

func (x *GeneralFilter) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

func (x *GeneralFilter) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GeneralFilter) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GeneralFilter) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *GeneralFilter) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *GeneralFilter) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

type Metadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         uint32                 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_transaction_transaction_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_transaction_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_transaction_transaction_proto_rawDescGZIP(), []int{6}
}

func (x *Metadata) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_transaction_transaction_proto protoreflect.FileDescriptor

const file_transaction_transaction_proto_rawDesc = "" +
	"\n" +
	"\x1dtransaction/transaction.proto\x12\rtransactionPb\x1a(google/api/annotations/annotations.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a)google/protobuf/timestamp/timestamp.proto\"n\n" +
	"\x0fTransactionList\x12.\n" +
	"\x04data\x18\x01 \x03(\v2\x1a.transactionPb.TransactionR\x04data\x12+\n" +
	"\x04meta\x18\x02 \x01(\v2\x17.transactionPb.MetadataR\x04meta\"\xdc\x01\n" +
	"\vTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\aid_name\x18\x02 \x01(\tR\x06idName\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12;\n" +
	"\vreturn_item\x18\x04 \x01(\v2\x1a.google.protobuf.BoolValueR\n" +
	"returnItem\x12\x1d\n" +
	"\n" +
	"sales_date\x18\x05 \x01(\tR\tsalesDate\x12\x12\n" +
	"\x04unit\x18\x06 \x01(\rR\x04unit\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\"=\n" +
	"\x0fGeneralResponse\x12*\n" +
	"\x04data\x18\x01 \x01(\v2\x16.transactionPb.GeneralR\x04data\"#\n" +
	"\aGeneral\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\"\n" +
	"\x10GeneralIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xb4\x01\n" +
	"\rGeneralFilter\x12\f\n" +
	"\x01q\x18\x01 \x01(\tR\x01q\x12\x19\n" +
	"\border_by\x18\x02 \x01(\tR\aorderBy\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\rR\x06offset\x12\x12\n" +
	"\x04sort\x18\x05 \x01(\tR\x04sort\x12\x1d\n" +
	"\n" +
	"start_date\x18\x06 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\a \x01(\tR\aendDate\" \n" +
	"\bMetadata\x12\x14\n" +
	"\x05count\x18\x01 \x01(\rR\x05count2\xf3\x04\n" +
	"\x12TransactionService\x12v\n" +
	"\x11CreateTransaction\x12\x1a.transactionPb.Transaction\x1a\x1e.transactionPb.GeneralResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/api/v1/transaction/create\x12\x80\x01\n" +
	"\x11DeleteTransaction\x12\x1f.transactionPb.GeneralIdRequest\x1a\x1e.transactionPb.GeneralResponse\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/api/v1/transaction/delete/{id}\x12t\n" +
	"\x12GetListTransaction\x12\x1c.transactionPb.GeneralFilter\x1a\x1e.transactionPb.TransactionList\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/api/v1/transaction/list\x12t\n" +
	"\x0eGetTransaction\x12\x1f.transactionPb.GeneralIdRequest\x1a\x1a.transactionPb.Transaction\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/api/v1/transaction/view/{id}\x12v\n" +
	"\x11UpdateTransaction\x12\x1a.transactionPb.Transaction\x1a\x1e.transactionPb.GeneralResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/api/v1/transaction/updateB3Z1github.com/YogiTan00/Reseller/proto;transactionPbb\x06proto3"

var (
	file_transaction_transaction_proto_rawDescOnce sync.Once
	file_transaction_transaction_proto_rawDescData []byte
)

func file_transaction_transaction_proto_rawDescGZIP() []byte {
	file_transaction_transaction_proto_rawDescOnce.Do(func() {
		file_transaction_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transaction_transaction_proto_rawDesc), len(file_transaction_transaction_proto_rawDesc)))
	})
	return file_transaction_transaction_proto_rawDescData
}

var file_transaction_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_transaction_transaction_proto_goTypes = []any{
	(*TransactionList)(nil),      // 0: transactionPb.TransactionList
	(*Transaction)(nil),          // 1: transactionPb.Transaction
	(*GeneralResponse)(nil),      // 2: transactionPb.GeneralResponse
	(*General)(nil),              // 3: transactionPb.General
	(*GeneralIdRequest)(nil),     // 4: transactionPb.GeneralIdRequest
	(*GeneralFilter)(nil),        // 5: transactionPb.GeneralFilter
	(*Metadata)(nil),             // 6: transactionPb.Metadata
	(*wrapperspb.BoolValue)(nil), // 7: google.protobuf.BoolValue
}
var file_transaction_transaction_proto_depIdxs = []int32{
	1, // 0: transactionPb.TransactionList.data:type_name -> transactionPb.Transaction
	6, // 1: transactionPb.TransactionList.meta:type_name -> transactionPb.Metadata
	7, // 2: transactionPb.Transaction.return_item:type_name -> google.protobuf.BoolValue
	3, // 3: transactionPb.GeneralResponse.data:type_name -> transactionPb.General
	1, // 4: transactionPb.TransactionService.CreateTransaction:input_type -> transactionPb.Transaction
	4, // 5: transactionPb.TransactionService.DeleteTransaction:input_type -> transactionPb.GeneralIdRequest
	5, // 6: transactionPb.TransactionService.GetListTransaction:input_type -> transactionPb.GeneralFilter
	4, // 7: transactionPb.TransactionService.GetTransaction:input_type -> transactionPb.GeneralIdRequest
	1, // 8: transactionPb.TransactionService.UpdateTransaction:input_type -> transactionPb.Transaction
	2, // 9: transactionPb.TransactionService.CreateTransaction:output_type -> transactionPb.GeneralResponse
	2, // 10: transactionPb.TransactionService.DeleteTransaction:output_type -> transactionPb.GeneralResponse
	0, // 11: transactionPb.TransactionService.GetListTransaction:output_type -> transactionPb.TransactionList
	1, // 12: transactionPb.TransactionService.GetTransaction:output_type -> transactionPb.Transaction
	2, // 13: transactionPb.TransactionService.UpdateTransaction:output_type -> transactionPb.GeneralResponse
	9, // [9:14] is the sub-list for method output_type
	4, // [4:9] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_transaction_transaction_proto_init() }
func file_transaction_transaction_proto_init() {
	if File_transaction_transaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transaction_transaction_proto_rawDesc), len(file_transaction_transaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transaction_transaction_proto_goTypes,
		DependencyIndexes: file_transaction_transaction_proto_depIdxs,
		MessageInfos:      file_transaction_transaction_proto_msgTypes,
	}.Build()
	File_transaction_transaction_proto = out.File
	file_transaction_transaction_proto_goTypes = nil
	file_transaction_transaction_proto_depIdxs = nil
}
